"""Structural tests for the new HTML renderer that consumes BadgeView."""

from __future__ import annotations

from cash.notebook.badge_renderer.renderers.html import (
    render_html,
    render_status_badge_html,
)
from cash.notebook.badge_renderer.view_builder import (
    build_interactive_badge,
    build_status_badge,
)
from cash.notebook.cache_status import CacheStatus


def test_empty_badge_produces_valid_html_skeleton() -> None:
    html = render_html(build_interactive_badge([]))
    assert "<details" in html
    assert "<summary" in html
    assert "<table" in html
    assert "EXECUTED" in html  # default status for an empty cell


def test_restored_row_shows_restored_label_and_saved_time() -> None:
    metrics = [{
        "code": "x = 1",
        "status": str(CacheStatus.RESTORED),
        "total_time": 0.001,
        "saved_time": 0.5,
        "source": "RAM",
    }]
    html = render_html(build_interactive_badge(metrics))
    assert "Restored" in html
    assert "Saved 0.50s" in html
    assert "← RAM" in html
    assert "CACHED" in html  # summary label


def test_computed_row_shows_executed_label_and_total_time() -> None:
    metrics = [{
        "code": "y = expensive()",
        "status": str(CacheStatus.COMPUTED),
        "total_time": 1.23,
        "evaluated_vars": ["y"],
        "storage": ["RAM", "DISK"],
    }]
    html = render_html(build_interactive_badge(metrics))
    assert "Executed" in html
    assert "1.23s" in html
    assert "y" in html
    assert "→ RAM+DISK" in html


def test_loop_iterations_render_as_collapsible_group() -> None:
    metrics = [
        {"code": "# __iteration_context__:loop1\ny = x*2",
         "status": str(CacheStatus.COMPUTED), "total_time": 0.01,
         "loop_vars": {"x": 1}},
        {"code": "# __iteration_context__:loop1\ny = x*2",
         "status": str(CacheStatus.COMPUTED), "total_time": 0.01,
         "loop_vars": {"x": 2}},
    ]
    html = render_html(build_interactive_badge(metrics))
    assert "iterations" in html
    assert "x=1" in html
    assert "x=2" in html
    assert "loop_stmt_" in html  # collapsible class generated by _uid


def test_skipped_bucket_renders_with_count_and_saved_time() -> None:
    metrics = [
        {"code": "step1", "status": str(CacheStatus.SKIPPED),
         "is_upstream": True, "saved_time": 0.3},
        {"code": "step2", "status": str(CacheStatus.SKIPPED),
         "is_upstream": True, "saved_time": 0.2},
    ]
    html = render_html(build_interactive_badge(metrics))
    assert "intermediate dependency steps" in html
    assert "Saved 0.50s" in html


def test_decorator_section_renders_when_calls_present() -> None:
    metrics = [{
        "code": "f()", "status": str(CacheStatus.COMPUTED), "total_time": 0.1,
        "decorator_calls": [
            {"func_name": "myf", "cache_hit": True, "execution_time": 0.001},
            {"func_name": "myf", "cache_hit": False, "execution_time": 0.05},
        ],
    }]
    html = render_html(build_interactive_badge(metrics))
    assert "DECORATOR CACHE" in html
    assert "myf()" in html
    assert "HIT" in html and "MISS" in html


def test_footer_present_when_bug_report_context_provided() -> None:
    metrics = [{"code": "x=1", "status": str(CacheStatus.COMPUTED), "total_time": 0.1}]
    html_no = render_html(build_interactive_badge(metrics))
    html_yes = render_html(build_interactive_badge(metrics, bug_report_context={"version": "1"}))
    assert "Report incorrect caching" not in html_no
    assert "Report incorrect caching" in html_yes


def test_overhead_section_appears_with_breakdown() -> None:
    metrics = [{"code": "x=1", "status": str(CacheStatus.COMPUTED), "total_time": 1.0}]
    html = render_html(build_interactive_badge(
        metrics,
        timing_breakdown={"badge_init": 0.05, "upstream_check": 0.02},
        cell_total_time=1.1,
    ))
    assert "Badge init" in html
    assert "Upstream check" in html


def test_status_badge_renders_compact_pill() -> None:
    html = render_status_badge_html(build_status_badge(
        status=CacheStatus.RESTORED, execution_time=0.01, time_saved=0.5,
        source="RAM", storage=["RAM"],
    ))
    assert "Restored" in html
    assert "Saved 0.50s" in html
    assert "← RAM" in html
    assert "RAM" in html


def test_running_state_summary_when_step_info_provided() -> None:
    html = render_html(build_interactive_badge(
        [], status="RUNNING", current_step=2, total_steps=5, current_code="z = slow()",
    ))
    assert "Processing (2/5)" in html
    assert "z = slow()" in html
