"""Render docs/_badges/<name>.html to <name>.png for surfaces that can't do HTML.

The docs site embeds the badge HTML in an iframe, which is the right thing
there -- it stays interactive. README.md cannot: GitHub and PyPI both strip
iframes, and PyPI strips <style> too. So the README gets a picture instead.

A picture is the one artifact in this repo that cannot be regenerated by
`pytest`, which is exactly how sample output goes stale. Hence this script and
`tests/test_docs/test_badge_images_fresh.py`: the PNG is a build product of the
committed HTML, and the test fails if the HTML moves without the PNG being
rebuilt. Chain of custody is renderer -> HTML (test_badge_examples_fresh)
-> PNG (test_badge_images_fresh).

Needs playwright with its bundled chromium (`pip install playwright &&
playwright install chromium`). Only maintainers regenerating badge art need
it -- the PNGs are committed, so a normal checkout, test run and docs build
never touch playwright.

Usage:  python scripts/build_badge_images.py [--only NAME ...]
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BADGE_DIR = REPO_ROOT / "docs" / "_badges"

# Only badges some non-HTML surface actually shows. Rendering all ~20 would
# commit binary art nothing references.
WANTED = ["status_mixed"]

# 2x so the image stays crisp on HiDPI; GitHub scales it down to fit.
SCALE = 2


def _stamp(html: pathlib.Path) -> str:
    return hashlib.sha256(html.read_bytes()).hexdigest()[:16]


def render(names: list[str]) -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "playwright is not installed. It is only needed to regenerate badge\n"
            "images, which are committed:\n"
            "    pip install playwright && playwright install chromium",
            file=sys.stderr,
        )
        return 2

    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(device_scale_factor=SCALE)
        for name in names:
            html = BADGE_DIR / f"{name}.html"
            if not html.exists():
                print(f"missing {html}; run build_badge_examples.py first", file=sys.stderr)
                return 1
            page.goto(html.as_uri())
            # The badge is a <details>, collapsed by default. A static image
            # of a collapsed badge shows one summary line and none of the
            # per-statement rows -- which are the whole point.
            page.evaluate(
                "document.querySelectorAll('details').forEach(d => d.open = true)"
            )
            card = page.locator(".c3-wrap")
            card.wait_for(state="visible")
            out = BADGE_DIR / f"{name}.png"
            card.screenshot(path=str(out))
            (BADGE_DIR / f"{name}.png.stamp").write_text(_stamp(html), encoding="utf-8")
            print(f"wrote {out.name} ({out.stat().st_size:,} bytes) from {name}.html")
        browser.close()
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", nargs="*", default=None, help="subset of badge names")
    args = ap.parse_args()
    return render(args.only or WANTED)


if __name__ == "__main__":
    raise SystemExit(main())
